#!/usr/bin/env python

import pst
import sys
import json

if sys.version_info[0] >= 3:
	import os
	s = b' '.join([os.fsencode(y) for y in sys.argv[1:]])
else:
	s = b' '.join(sys.argv[1:])

print(json.dumps(pst.decode(s, True), ensure_ascii=False))
