#!/usr/bin/env python

import pst
import sys
import json

if sys.version_info[0] >= 3:
	import os
	args = [os.fsencode(y) for y in sys.argv[1:]]
else:
	args = sys.argv[1:]

print(json.dumps(pst.decode(args, True), ensure_ascii=False))
